### ISSUE TITLE
DynamicBatteryStorage probably conflicts with a mod and doesn´t load

### ISSUE THREAD

**Issue by iGGnite** [ChrisAdderley/DynamicBatteryStorage#19]
Hello, I was told to share this issue and I hope I´m in the right place.
An exception is thrown when loading the game, I have a lot of mods and am not a mod maker so I can´t tell you much more, DBS doesn´t work in-game. Here are my mod list and my KSP.log so you can orient yourself:
![36c558535ab27d6c32986cd60b25706b](https://user-images.githubusercontent.com/36937528/56574141-cf731f80-65c2-11e9-8b93-76806c7ddba1.png)
[KSP.log](https://github.com/ChrisAdderley/DynamicBatteryStorage/files/3107064/KSP.log)

**Comment by ChrisAdderley** [comment]
The log shows a target framework exception, which was fixed with DBS 1.4.2 yesterday. I suggest installing that. 

However that being said, reading the log shows DBS operating properly. I'm curious, how did you figure out it was not working?

**Comment by iGGnite** [comment]
When time warping while using a good amount of EC my batteries don't increase in size, having caused my kerbals to go tourist mode.

**Comment by iGGnite** [comment]
I'll download the update, thanks

**Comment by iGGnite** [comment]
Hello, I installed the updated version and DMS is still not working as far as I can tell. While time-warping, I continuously run out of EC, because the EC capacity doesn't dynamically increase with warp speed.
[KSP.log](https://github.com/ChrisAdderley/DynamicBatteryStorage/files/3111462/KSP.log)

**Comment by ChrisAdderley** [comment]
Well, I tested in a basic installation just now and everything worked fine. 

Your log doesn't show me anything I can use to debug things unfortunately. I will need
1. A description of the spacecraft's power using and power producing parts (best to show a screenshot with all the relevant part right click windows open) 
2. A screenshot of the DBS debug window when active, using `CTRL+SHIFT+K` ( only appears at >1000x warp)
3. Preferably, a minimum-reproducable test case - a set of steps that I can take myself that reproduces the issue (minimum/no other mods, etc).

**Comment by iGGnite** [comment]
Could you provide me with a stock vessel so that I can test DBS. Then I can figure out when it stops working after a certain mod.

**Comment by ChrisAdderley** [comment]
I don't think that's necessarily going to help anything. My suspicion is that your craft is using some combination of unsupported power consumers and unsupported power generators. 

But since you asked, an easy test is to build the following craft (not stock, it's quite hard to trigger scenarios with stock):

- Mk1 command pod
- NFE 0.625m reactor
- 8x Small Thermal Control Systems

Turn on reactor, extend radiators. This should be enough generation capacity and power draw to trigger some kind of effect.
